### ISSUE TITLE
Unpredictable behavior for different sources

### ISSUE THREAD

**Issue by languitar** [ncm2/ncm2-abbrfuzzy#2]
I have a language server running and the bufword source. Somehow, despite both sources being able to provide the same words for completion, the matching seems to behave differently on them:

![2018-07-13t13 18 58 02 00](https://user-images.githubusercontent.com/1336287/42689169-89207864-869f-11e8-9e9b-805086257213.png)
![2018-07-13t13 19 14 02 00](https://user-images.githubusercontent.com/1336287/42689170-89410480-869f-11e8-97b7-0ba055ad204e.png)

I would expect both sources to respond in both cases.

**Comment by roxma** [comment]
Make sure your installation of ncm2 plugins are the latest version.

Some old version of ncm2 have this issue.

If the issue still exists, I need minimal vimrc to reproduce the issue.

**Comment by roxma** [comment]
abbrfuzzy is not builtin in ncm2.

This repo is deprecated.

Closing...
